// Projects
export const highlightProject = [
  {
    img: "/project-7.webp",
    name: "North Star",
    desc: "A calmer way for teams to plan, focus, and ship meaningful work.",
    type: "Product design",
    href: "https://northstar.vercel.app",
    year: "2026",
  },
  {
    img: "/project-8.webp",
    name: "Sora Studio",
    desc: "A visual identity and digital home for a new generation of makers.",
    type: "Brand & web",
    href: "https://sorastudio.vercel.app",
    year: "2026",
  },
  {
    id: "atlas-finance",
    img: "/project-5.webp",
    name: "Atlas Finance",
    desc: "A clearer financial dashboard for people building better money habits.",
    type: "Web application",
    href: "https://atlas-finance.vercel.app",
    year: "2026",
  },
  {
    id: "field-notes",
    img: "/project-4.webp",
    name: "Field Notes",
    desc: "A thoughtful publishing platform for independent writers and creators.",
    type: "Editorial platform",
    href: "https://field-notes.vercel.app",
    year: "2026",
  },
];

export const allProjects = [
  {
    id: "north-star",
    img: "/project-1.webp",
    name: "North Star",
    desc: "A calmer way for teams to plan, focus, and ship meaningful work.",
    type: "Product design",
    href: "https://northstar.vercel.app/?ref=",
    year: "2026",
  },
  {
    id: "sora-studio",
    img: "/project-2.webp",
    name: "Sora Studio",
    desc: "A visual identity and digital home for a new generation of makers.",
    type: "Brand & web",
    href: "https://sorastudio.vercel.app",
    year: "2026",
  },
  {
    id: "atlas-finance",
    img: "/project-3.webp",
    name: "Atlas Finance",
    desc: "A clearer financial dashboard for people building better money habits.",
    type: "Web application",
    href: "https://atlas-finance.vercel.app",
    year: "2026",
  },
  {
    id: "field-notes",
    img: "/project-4.webp",
    name: "Field Notes",
    desc: "A thoughtful publishing platform for independent writers and creators.",
    type: "Editorial platform",
    href: "https://field-notes.vercel.app",
    year: "2026",
  },
  {
    id: "morrow-house",
    img: "/project-5.webp",
    name: "Morrow House",
    desc: "A refined digital home for a hospitality brand built around slow living.",
    type: "Hospitality & web",
    href: "https://morrow-house.vercel.app",
    year: "2026",
  },
  {
    id: "kindred-health",
    img: "/project-6.webp",
    name: "Kindred Health",
    desc: "A more human way for patients to discover care and book appointments.",
    type: "Healthcare product",
    href: "https://kindred-health.vercel.app",
    year: "2026",
  },
  {
    id: "common-ground",
    img: "/project-7.webp",
    name: "Common Ground",
    desc: "A community platform helping local teams organize meaningful events.",
    type: "Community platform",
    href: "https://common-ground.vercel.app",
    year: "2026",
  },
  {
    id: "form-and-function",
    img: "/project-8.webp",
    name: "Form & Function",
    desc: "A digital catalogue for a studio making useful objects for everyday life.",
    type: "E-commerce experience",
    href: "https://form-and-function.vercel.app",
    year: "2026",
  },
];
// Pricing
export const pricingList = [
  {
    id: "starter",
    title: "STARTER SITE",
    price: "From $765",
    desc: "For a focused launch that gives your business a polished, credible home online.",
    feature: [
      "Up to 1 pages",
      "Responsive design",
      "WhatsApp / contact CTA",
      "Launch-ready in 5 days",
    ],
    href: "/contact?plan=starter",
    linkName: "Discuss your project",
    style: "light",
  },
  {
    id: "growth",
    title: "GROWTH WEBSITE",
    price: "From $1,500",
    desc: "For brands ready to stand out, explain their value, and turn more visits into enquiries.",
    feature: [
      "Up to 4 pages",
      "Custom visual direction",
      "SEO foundations",
      "Conversion-focused structure",
      "Launch-ready in 7 days",
    ],
    href: "/contact?plan=growth",
    linkName: "Choose the right fit",
    style: "dark",
    popular: true,
  },
  {
    id: "signature",
    title: "SIGNATURE BUILD",
    price: "From $2,500",
    desc: "For ambitious teams that need a distinctive digital experience built around their next stage.",
    feature: [
      "Up to 8 pages",
      "Strategy + custom design",
      "Advanced interactions",
      "CMS or property listings",
      "Post-launch support",
      "Launch-ready in 14 days",
    ],
    href: "/contact?plan=signature",
    linkName: "Plan something bigger",
    style: "light",
  },
];
